name: Build Flutter APK's and App bundle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    # branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./livewell
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Prepare release keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" > signing_config.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FILE_BASE64_PASSPHRASE }}" --batch signing_config.jks.asc > signing_config.jks
      - name: ðŸ“ðŸ” Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ./android/key.properties
        run: |
          echo 'StoreFile=./signing_config.jks' > $KEYSTORE_PROPERTIES_PATH
          echo 'KeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'StorePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'KeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
        

      # Set up Flutter.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v
      # Checkout the repository code and get packages.
      - name: Checkout flutter_app code
        uses: actions/checkout@v3
      - run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build APP BUNDLE
        run: flutter build appbundle

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk, build/app/outputs/bundle/release/*.aab"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release-apk
          path: build/app/outputs/apk/
